// Auto-generated by cbindgen. Do not edit.

#ifndef MACVIBER_CORE_H
#define MACVIBER_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PaneSize_MINIMUM_WIDTH 300.0

#define PaneSize_MINIMUM_HEIGHT 200.0

typedef void *CoreHandle;

typedef uint8_t SessionId[16];

typedef void (*OutputCallback)(const uint8_t*, uintptr_t, void*);

CoreHandle core_init(void);

void core_destroy(CoreHandle handle);

int32_t core_create_session(CoreHandle handle, const char *working_dir, SessionId *out_session_id);

int32_t core_close_session(CoreHandle handle, const SessionId *session_id);

int32_t core_session_count(CoreHandle handle);

const char *core_version(void);

int32_t core_set_output_callback(CoreHandle _handle, const SessionId *_session_id, OutputCallback _callback, void *_context);

int32_t core_send_input(CoreHandle _handle, const SessionId *_session_id, const uint8_t *_input, uintptr_t _len);

#endif /* MACVIBER_CORE_H */
