// Auto-generated by cbindgen. Do not edit.

#ifndef MACVIBER_CORE_H
#define MACVIBER_CORE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PaneSize_MINIMUM_WIDTH 300.0

#define PaneSize_MINIMUM_HEIGHT 200.0

typedef void *CoreHandle;

typedef uint8_t SessionId[16];

typedef void (*OutputCallback)(const uint8_t*, uintptr_t, void*);

typedef void *PatternMatcherHandle;

typedef struct PatternMatchResult {
  bool matched;
  SessionId patternId;
  bool autoPin;
} PatternMatchResult;

typedef void *NotificationDetectorHandle;

typedef struct DetectionResult {
  bool detected;
  int32_t notificationType;
  char *message;
  SessionId notificationId;
} DetectionResult;

typedef void *SplitViewStateHandle;

CoreHandle core_init(void);

void core_destroy(CoreHandle handle);

int32_t core_create_session(CoreHandle handle, const char *working_dir, SessionId *out_session_id);

int32_t core_close_session(CoreHandle handle, const SessionId *session_id);

int32_t core_session_count(CoreHandle handle);

const char *core_version(void);

int32_t core_set_output_callback(CoreHandle _handle, const SessionId *_session_id, OutputCallback _callback, void *_context);

int32_t core_send_input(CoreHandle _handle, const SessionId *_session_id, const uint8_t *_input, uintptr_t _len);

PatternMatcherHandle pattern_matcher_create(void);

void pattern_matcher_destroy(PatternMatcherHandle handle);

int32_t pattern_matcher_add_pattern(PatternMatcherHandle handle, const SessionId *pattern_id, const char *name, const char *pattern, bool is_regex, bool is_enabled, bool auto_pin);

int32_t pattern_matcher_remove_pattern(PatternMatcherHandle handle, const SessionId *pattern_id);

int32_t pattern_matcher_match(PatternMatcherHandle handle, const char *text, struct PatternMatchResult *out_result);

void pattern_matcher_invalidate_cache(PatternMatcherHandle handle);

NotificationDetectorHandle notification_detector_create(void);

void notification_detector_destroy(NotificationDetectorHandle handle);

int32_t notification_detector_detect(NotificationDetectorHandle handle, const char *text, const SessionId *session_id, struct DetectionResult *out_result);

void notification_detector_reset(NotificationDetectorHandle handle);

void free_string(char *s);

SplitViewStateHandle split_view_state_create(void);

void split_view_state_destroy(SplitViewStateHandle handle);

bool split_view_state_is_active(SplitViewStateHandle handle);

int32_t split_view_state_pane_count(SplitViewStateHandle handle);

bool split_view_state_can_split(SplitViewStateHandle handle);

int32_t split_view_state_enter(SplitViewStateHandle handle, const SessionId *session_id);

void split_view_state_exit(SplitViewStateHandle handle);

int32_t split_view_state_split_pane(SplitViewStateHandle handle, const SessionId *pane_id, int32_t direction, const SessionId *new_session_id, double width, double height, SessionId *out_new_pane_id);

int32_t split_view_state_close_pane(SplitViewStateHandle handle, const SessionId *pane_id);

int32_t split_view_state_get_focused_pane_id(SplitViewStateHandle handle, SessionId *out_pane_id);

int32_t split_view_state_set_focused_pane_id(SplitViewStateHandle handle, const SessionId *pane_id);

int32_t split_view_state_next_pane(SplitViewStateHandle handle, SessionId *out_pane_id);

int32_t split_view_state_previous_pane(SplitViewStateHandle handle, SessionId *out_pane_id);

int32_t split_view_state_get_session_for_pane(SplitViewStateHandle handle, const SessionId *pane_id, SessionId *out_session_id);

int32_t split_view_state_get_all_pane_ids(SplitViewStateHandle handle, SessionId *out_ids, int32_t max_count);

#endif /* MACVIBER_CORE_H */
